# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjQ2OGUyODQ5ZGFmZjlmN2I1ODViNGE3YWYwYWEyZTRmNWJiOWFhYzVmZGQ0ODkzM2MyYjliNjJhMjYwYjgxMjkxNWRkMjk1ZWVhMWFjNGM3MWQ3NGU5NGVmMzg2YTJiMTdhNDk3MDFhMjE5NTBhNDU3NmZiYTU3MjNkODZiODA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
